apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  annotations:
    keel.sh/policy: force
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: namarot/cs_app:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: api-config
          resources:
            requests:
              cpu: "200m"
          imagePullPolicy: Always